;;;; src/text.lisp
;;;;
;;;; Case-aware text predicates.  Every matcher in the library funnels through
;;;; these four, so "case sensitive" and "smartcase" each have exactly one
;;;; definition instead of one per call site -- search and navigation can never
;;;; drift apart on what counts as a match.  Three of the four, plus the
;;;; line-boundary variant %LINE-PREFIX-MATCH-P, are generated by
;;;; DEFINE-CASE-SENSITIVE-PREDICATE from the guard/comparison forms that
;;;; actually distinguish them, rather than each restating the CASE-SENSITIVE
;;;; dispatch and boolean coercion by hand.
(in-package #:history-kit)

(defun %smartcase-sensitive-p (query)
  "True when QUERY should be matched case-sensitively under the smartcase rule.

A query containing an upper-case character is matched case-sensitively, an
all-lower-case one case-insensitively.  This is the familiar Vim/fish
convention: typing in lower case searches loosely, and reaching for the shift
key is taken as an explicit request for precision."
  (and (some #'upper-case-p query) t))

(defmacro define-case-sensitive-predicate
    (name (text query &rest extra-params) documentation
     &key bindings guard sensitive insensitive)
  "Define NAME as (TEXT QUERY . EXTRA-PARAMS &key CASE-SENSITIVE), generated
from data rather than written out by hand: BINDINGS are LET* clauses shared
by both branches, GUARD is an optional extra condition evaluated before the
comparison, and SENSITIVE/INSENSITIVE are the two comparison forms CASE-
SENSITIVE chooses between. Every text predicate in this file reduces to
exactly that shape -- a guard plus a case-sensitive/insensitive pair over
STRING=/STRING-EQUAL or SEARCH -- so the shape is data here and the
CASE-SENSITIVE dispatch and boolean coercion are logic defined once."
  `(defun ,name (,text ,query ,@extra-params &key case-sensitive)
     ,documentation
     (let* ,bindings
       (and ,@(when guard (list guard))
            (if case-sensitive ,sensitive ,insensitive)
            t))))

(define-case-sensitive-predicate %text-prefix-p (text query)
  "True when TEXT begins with QUERY."
  :bindings ((query-length (length query)))
  :guard (<= query-length (length text))
  :sensitive (string= text query :end1 query-length)
  :insensitive (string-equal text query :end1 query-length))

(define-case-sensitive-predicate %text-equal-p (text query)
  "True when TEXT equals QUERY in its entirety."
  :sensitive (string= text query)
  :insensitive (string-equal text query))

(define-case-sensitive-predicate %text-contains-p (text query)
  "True when QUERY occurs anywhere within TEXT."
  :sensitive (search query text)
  :insensitive (search query text :test #'char-equal))

(defun %map-lines (function text)
  "Call FUNCTION with the start and end index of each line of TEXT, returning
the first non-NIL result.

A recorded command can span several lines, and both line-prefix search and
prefix navigation want to match any one of them -- not only the first -- so
that recalling a multi-line command by its second line works."
  (loop with length = (length text)
        with line-start = 0
        for newline = (position #\Newline text :start line-start)
        for line-end = (or newline length)
        thereis (funcall function line-start line-end)
        while newline
        do (setf line-start (1+ newline))))

(define-case-sensitive-predicate %line-prefix-match-p (text query line-start line-end)
  "True when the line of TEXT spanning [LINE-START, LINE-END) begins with QUERY."
  :bindings ((query-end (+ line-start (length query))))
  :guard (<= query-end line-end)
  :sensitive (string= text query :start1 line-start :end1 query-end)
  :insensitive (string-equal text query :start1 line-start :end1 query-end))

(defmacro with-each-line ((line-start line-end text) &body body)
  "Evaluate BODY with LINE-START and LINE-END bound to the start and end
index of each line of TEXT in turn, stopping at the first non-NIL result --
the binding-form spelling of the FUNCALL-based %MAP-LINES, for call sites
that want a line-scanning loop rather than a function to hand it."
  `(%map-lines (lambda (,line-start ,line-end) ,@body) ,text))

(defun %text-line-prefix-p (text query &key case-sensitive)
  "True when any line of TEXT begins with QUERY."
  (and (with-each-line (line-start line-end text)
         (%line-prefix-match-p text query line-start line-end
                               :case-sensitive case-sensitive))
       t))

(defun %text-line-suffix (text query &key case-sensitive)
  "Return the remainder of the first line of TEXT that begins with QUERY.

Returns NIL when no line begins with QUERY, and the empty string when a line
consists of QUERY exactly -- the two are distinguishable, which is what an
autosuggestion consumer needs in order to tell \"nothing to suggest\" from
\"already complete\"."
  (with-each-line (line-start line-end text)
    (when (%line-prefix-match-p text query line-start line-end
                                :case-sensitive case-sensitive)
      (subseq text (+ line-start (length query)) line-end))))
